export const storageKeys = {
  language: 'language',
  signInMethod: 'sign-in-method',
  user: 'user',
  meetings: 'meetings',
  requests: 'requests',
  groups: 'groups',
  friends: 'friends',
  friendInvitations: 'friend-invitations',
  meetingInvitations: 'meeting-invitations',
  push: 'push',
  pushTopicUser: 'push-topic-user',
  pushTopicAll: 'push-topic-all',
  pushTopicPlatform: 'push-topic-platform',
  lastRequestForm: 'last-request-form',
};
